prometheus:
  prometheusSpec:
    # Prevents fallback to Helm values when selectors are nil
    serviceMonitorSelectorNilUsesHelmValues: false

    # Selects all ServiceMonitors in all namespaces
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    # Selects PrometheusRule resources labeled with 'prometheus=practical-rules'
    ruleSelector:
      matchExpressions:
        - key: prometheus
          operator: In
          values:
            - practical-rules

grafana:
  sidecar:
    datasources:
      # Enables default Prometheus datasource injection
      defaultDatasourceEnabled: true

  additionalDataSources:
    # Adds Loki as an additional datasource for log querying
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-query-frontend.monitoring:3100

alertmanager:
  config:
    global:
      # Time to wait before marking alerts as resolved
      resolve_timeout: 5m

      # Slack webhook URL for sending alert notifications
      slack_api_url: "https://hooks.slack.com/services/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"

    route:
      # Group alerts by 'job' label
      group_by: ['job']
      group_wait: 30s           # Delay before first notification
      group_interval: 5m        # Minimum interval between alerts in a group
      repeat_interval: 12h      # How often to resend unresolved alerts
      receiver: 'slack'         # Default receiver

      routes:
        # Silences DeadMansSwitch alerts
        - match:
            alertname: DeadMansSwitch
          receiver: 'null'

        # Catch-all route for other alerts
        - match:
          receiver: 'slack'
          continue: true

    receivers:
      # Null receiver to discard alerts
      - name: 'null'

      # Slack receiver configuration
      - name: 'slack'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Annotations.description }}
                *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}

